openapi: 3.0.3
info:
  title: Body Measures Flask API
  version: 1.0.0
  description: REST API built with Flask for a body measurement tracking application.
  contact:
    name: Suporte da API
    email: bernardoboggionechamilet@gmail.com
servers:
  - url: http://localhost:5000
    description: Servidor local de desenvolvimento
paths:
  /login:
    post:
      summary: Login
      description: Verifica dados e retorna ou não token
      tags:
        - Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/login/login_req_body.yaml'
      responses:
        '200':
          description: Login efetuado com sucesso
          content:
            application/json:
              schema:
                $ref: './components/schemas/login/login_res.yaml' 
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: email ou senha não são strings
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Senha incorreta
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /usuarios:
    post:
      summary: Cadastrar usuário
      description: Cadastra um novo usuário e retorna seu id
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/usuarios/cadastrar_usuario_req_body.yaml'
      responses:
        '201':
          description: Usuário criado
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/cadastrar_usuario_res.yaml'
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Senha deve ter pelo menos 6 caracteres
        '409':
          description: Conflito
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Usuário já existe
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    get:
      summary: Listar usuários
      description: Lista todos usuários cadastrados
      tags:
        - Usuários
      responses:
        '200':
          description: Usuários listados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/usuarios/nao_sensiveis.yaml'
        '204':
          description: Sem conteúdo
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /usuarios/me:
    get:
      summary: Buscar usuário logado
      description: Busca dados exceto a senha do usuário logado
      parameters:
        - $ref: './components/parameters/jwt.yaml'
      tags:
        - Usuários
      responses:
        '200':
          description: Dados do usuário buscados
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/nao_sensiveis.yaml'
        '204':
          description: Sem conteúdo
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /usuarios/{id}:
    get:
      summary: Buscar usuário por id
      description: Busca dados exceto a senha de um usuário por id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_usuario.yaml'
      tags:
        - Usuários
      responses:
        '200':
          description: Dados do usuário buscados
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/nao_sensiveis.yaml'
        '204':
          description: Sem conteúdo
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    put:
      summary: Atualizar usuário
      description: Atualiza dados exceto a senha de um usuário com determinado id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_usuario.yaml'
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/usuarios/atualizar_usuario_req_body.yaml'
      responses:
        '204':
          description: Usuário atualizado (sem conteúdo)
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Usuario deve ter pelo menos 7 caracteres
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '403':
          description: Proíbido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Somente pode atualizar os próprios dados
        '404':
          $ref: './components/responses/not_found_usuario.yaml'
        '409':
          description: Conflito
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Usuário já existe
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    delete:
      summary: Deletar usuário
      description: Deleta dados de um usuário com determinado id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_usuario.yaml'
      tags:
        - Usuários
      responses:
        '200':
          description: Dados do usuário deletados
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/cadastrar_usuario_res.yaml'
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '403':
          description: Proíbido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Somente pode deletar a prórpria conta
        '404':
          $ref: './components/responses/not_found_usuario.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /usuarios/{id}/atualizar-senha:
    patch:
      summary: Atualizar senha
      description: Atualiza a senha de um usuário com determinado id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_usuario.yaml'
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/usuarios/atualizar_senha_req_body.yaml'
      responses:
        '204':
          description: Senha atualizada (sem conteúdo)
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Nova senha não pode ser igual a senha atual
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '403':
          description: Proíbido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Somente pode atualizar os próprios dados
        '404':
          $ref: './components/responses/not_found_usuario.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /medidas:
    post:
      summary: Registrar medida
      description: Registra nova medida e retorna seu id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
      tags:
        - Medidas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/medidas/registrar_medida_req_body.yaml'
      responses:
        '201':
          description: Medida registrada
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/cadastrar_usuario_res.yaml'
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Algum campo em formato inválido
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    get:
      summary: Listar medidas
      description: Lista todas medidas do usuário logado
      parameters:
        - $ref: './components/parameters/jwt.yaml'
      tags:
        - Medidas
      responses:
        '200':
          description: Medidas listadas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components/schemas/medidas/buscar_medida_res.yaml'
        '204':
          description: Usuário logado não possui medidas
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
  /medidas/{id}:
    get:
      summary: Buscar medida por id
      description: Busca uma medida por id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_medida.yaml'
      tags:
        - Medidas
      responses:
        '200':
          description: Medida buscada
          content:
            application/json:
              schema:
                $ref: './components/schemas/medidas/buscar_medida_res.yaml'
        '204':
          description: Sem conteúdo
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    put:
      summary: Atualizar medida
      description: Atualiza medida com determinado id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_medida.yaml'
      tags:
        - Medidas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components/schemas/medidas/registrar_medida_req_body.yaml'
      responses:
        '204':
          description: Medida atualizada (sem conteúdo)
        '400':
          description: Requisição mal feita
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Algum campo em formato inválido
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '403':
          description: Proíbido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Somente pode atualizar as próprias medidas
        '404':
          $ref: './components/responses/not_found_medida.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'
    delete:
      summary: Deletar medida
      description: Deleta medida com determinado id
      parameters:
        - $ref: './components/parameters/jwt.yaml'
        - $ref: './components/parameters/id_medida.yaml'
      tags:
        - Medidas
      responses:
        '200':
          description: Medida deletada
          content:
            application/json:
              schema:
                $ref: './components/schemas/usuarios/cadastrar_usuario_res.yaml'
        '401':
          $ref: './components/responses/nao_autorizado_token.yaml'
        '403':
          description: Proíbido
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Somente pode deletar as próprias medidas
        '404':
          $ref: './components/responses/not_found_medida.yaml'
        '500':
          $ref: './components/responses/internal_server_error.yaml'